// Единый список имён маршрутов

export enum ERouteNames {
    PAGE_NOT_FOUND = 'page-not-found', // Путь для несуществующих страниц
    LOGIN = 'login', // Страница авторизации
    USER_PROFILE = 'profile', // Страничка с профилем пользователя
    HOME = 'home', // Главная точка входа с AppLayout
    DASHBOARD = 'dashboard', // Панель пользователя
    ADVERSE_EVENTS = 'adverse-events', // Список нежелательных событий
    ADVERSE_EVENT_DETAIL = 'detail-adverse-event', // Единый путь на форму
    CREATE_ADVERSE_EVENT = 'create-adverse-event', // Создание нового НС
    SUPPORT_SERVICE = 'support-service', // Заявки в вспомогательные службы
    SUPPORT_SERVICE_DETAIL = 'detail-support-service', // Единый путь на форму
    CREATE_SUPPORT_SERVICE = 'create-support-service', // Создание новой заявки
    TICKETS = 'tickets', // Список тикетов
    TICKET_DETAIL = 'ticket-detail', // Детальная страница тикета
    CREATE_TICKET = 'create-ticket', // Создание тикета
    CALENDAR = 'calendar', // Календарь
    CURRENT_CALENDAR = 'current-calendar', // Текущий календарь по id
    ADMIN = 'admin', // Админская точка входа с AppLayout
    ADMIN_DASHBOARD = 'admin-dashboard', // Панель администратора
    ADMIN_EMPLOYEE_POSITION = 'admin-employee-position', // Управление должностями
    ADMIN_BUILDINGS = 'admin-buildings', // Управление зданиями
    ADMIN_DEPARTMENTS = 'admin-departments', // Управление отделами
    ADMIN_ROOMS = 'admin-rooms', // Управление помещениями
    ADMIN_EMPLOYEES = 'admin-employees', // Управление сотрудниками
    ADMIN_ROOM_TYPES = 'admin-room-types', // Управление типами помещений
    ADMIN_FLOORS = 'admin-floors', // Управление этажами
    ADMIN_ADVERSE_EVENT_TYPES = 'admin-adverse-event-types', // Типы нежелательных событий
    ADMIN_EVENT_CATEGORIES = 'admin-event-categories', // Категории НС
    EDIT_ADMIN_ADVERSE_EVENT_CATEGORIES = 'edit-admin-adverse-event-categories', // Редактирование категории НС по id
    CREATE_ADMIN_ADVERSE_EVENT_CATEGORIES = 'create-admin-adverse-event-categories', // Создание категории НС
    SURGICAL_OPERATION = 'surgical-operation', // Компонент заглушка (Операции)
    STAFF = 'staff', // Компонент заглушка (Кадры)
    ANALYTICS = 'analytics', // Компонент заглушка (Аналитика)
    JOURNALS = 'journals', // Компонент заглушка (Журналы)
    CONSULTATIONS = 'consultations', // Компонент заглушка (Консультации)
    PURCHASES = 'purchases', // Компонент заглушка (Закупки)
    NOTIFICATION = 'notification', // Компонент заглушка (Извещения)
    LINKS = 'links', // Компонент полезные ссылки
    CHAT = 'chat', // Модуль чатов
    FILES = 'files', // Файлы сотрудников
    IMPROVEMENTS = 'improvements', // Предложения по улучшению
    DOCUMENTS = 'documents', // Реестр документов МИС
    DOCUMENTS_FOLDER = 'documents-folder', // Документы конкретной папки
    DOCUMENT_DETAIL = 'document-detail',
    DOCUMENT_CREATE = 'document-create',
    DOCUMENT_EDIT = 'document-edit',
    ACTUAL = 'actual', // Актуальное
    ACTUAL_DETAIL = 'actual-detail',
    ACTUAL_CREATE = 'actual-create',
    ACTUAL_EDIT = 'actual-edit',
    NEWS = 'news', // Новости
    NEWS_DETAIL = 'news-detail',
    CREATE_CALENDAR_EVENT = 'create-calendar-event',
    EDIT_CALENDAR_EVENT = 'edit-calendar-event',
    VIEW_CALENDAR_EVENT = 'view-calendar-event',
    HEATMAP = 'heatmap'
}
